### PR TITLE
#35 - Update fr_FR last names and prefixes.

### LINKED ISSUE #35: review: see about fr_FR last names and prefixes
> This may not be terribly important for the applications this package would be used for, but the method for names in "fr_FR" of adding random prefixes to some names is going to result in some funky last names in that language ("de la Dufour", "du Olivier", "Le Lemonnier"). Also, why do none of the French last names have accents in them, while the first names do? Will this matter in anticipated applications?

### PR DESCRIPTION
**Pull request by kylevoyto**
Added accent markers to fr_FR last names (copied from Ruby Faker).
Updated fr_FR prefixes to fix a few awkward last names.

## Description (detail included so that there's a record of the reasoning behind the changes)
fr_FR last names did not have any accents while first names did.

To track down a list of French surnames with accents, I looked at the Python Faker, PHP Faker, and Ruby Faker libraries. Python and PHP had the exact list of 400 names included in charlatan. Ruby, however, had a shorter list of 150 names which included 88 names with accents. The accents were added in May 2018 (https://github.com/stympy/faker/commit/ed0cb460b6f91e6989f00c0c3ec86b6fc27a7bb6). It seems like an accent was added to 'e' in most names. I cannot tell whether the change made the names more natural, but I believe it's an improvement on the current list. I changed 88 of the 400 names in charlatan to include accent marks ported from Ruby Faker.

The fr_FR prefixes can produce awkward names in the French language.

I attempted to research French prefixes on the [French name Wikipedia page](https://en.wikipedia.org/wiki/French_name#Particles). There are last names with "De", "de", "Du", "Le", "La". In order to get an idea of French names in culture, I looked at the [List of French people Wikipedia page](https://en.wikipedia.org/wiki/List_of_French_people). Searching the page for the articles list above revealed that "de" seems to be more common in French names while the others are used less commonly.

Another consideration is that the last name list in charlatan contained a few names with prefixes already attached ("Le Gall", "Le Roux", "Le Goff", "Da Silva", "Da Costa", "De Oliveira", "De Sousa", and "Dos Santos"). Combined with the prefixes in charlatan, they could produce awkward names "de La Le Gall". Hyphenated names could also be affected, "Gallet-Da Silva".

I could not decide the best approach for prefixes. It seems like they're used fairly commonly in French surnames. As a balancing act between no prefixes and awkward prefixes, I decided to remove all of the prefixes from set last names, "Le Gall" -> "Gall", but keep a few of the (seemingly) common prefixes in the prefixes variable ("de", "de La", "Le"). I think this may cause issues with word gender and meaning, but it will at least fix the worst of the prefix issues.

## Related Issue
fix #35

## Example
`x <- ch_name(100, locale = "fr_FR")`
`x`

### CODE REVIEW

**Comment by sckott** [comment]
thanks @kylevoyto !  Thanks for all the details and for documenting the reasoning. This is great. If you don't mind I'd like to get my french colleague @maelle to have a quick look. Do you have a bit of time Maëlle to take a look? if so pull down changes for this PR, then run e.g., `ch_name(100, locale = "fr_FR")` any number of times to see what comes out. Curious to get your sense if there's any major problems.

**Comment by maelle** [comment]
Cool, will look tomorrow

**Comment by sckott** [comment]
thanks @maelle !

**Comment by maelle** [comment]
Merci bien, @kylevoyto !

Taking notes as I go. I forgot to set the random seed! 🙀 

* I got "Margot-Margot Blot". I see "Margot" is twice in the list of first names, it'd make sense to only keep unique names. It'd also be nice for the vectors to be alphabetically ordered.

* I actually got several names with the same first name / last name duplicated, apparently all names with double first name have the same unit duplicated, and it happens for some last names. Margot-Margot Blot, Nathalie-Nathalie Marchal, Auguste Pons-Pons. I don't think this is a bug introduced by this PR though, but going forward it'd be cool if `charlatan` used double first/last names are distinct.

* Regarding prefixes, before vowels it looks very weird to me to have "Le" or "La", it should be "L'" to look more real. Same with "de", it should be "d'" before vowels.

* Again not something linked to this PR, but it'd be nice to have more diverse first/last names, e.g. see the French male soccer team for inspiration, "N'Golo" can be a French first name and the "'" in the name might be important for applications of this package.

* Any idea what the distinction between fr-FR and fr-CH is based on?

**Comment by sckott** [comment]
thanks very much for the help on this @maelle !

@kylevoyto do you think you can incorporate her feedback? 

i think `fr-CH` is swiss french http://www.localeplanet.com/icu/fr-CH/index.html

**Comment by sckott** [comment]
@maelle sorry! 🙈 I don't know. From your perspective, would you not expect different names?

**Comment by maelle** [comment]
I'm not sure I'd expect different names, I'd just expect more names from the other Swiss languages. Maybe the reasons for having 2 lists and conventions is explained in the other faker packages?

**Comment by maelle** [comment]
Let me experiment a bit with wikidata, you inspired me @kylevoyto 🤔

**Comment by maelle** [comment]
At the risk of going beyond the scope of this PR and package... 

Wikidata seems interesting if there's interest (but it's a biased sample of course!). It'd help getting names, and occupations, in any locale: changing the language of the Wikibase, and the filter near P27 (country of citizenship). Here I use Q142 for France, but for Switzerland I would just need to use

``` r
WikidataR::find_item("Switzerland", limit = 1)
#> 
#>  Wikidata item search
#> 
#> Number of results:    1 
#> 
#> Results:
#> 1     Switzerland (Q39) - federal republic in Western Europe
```

Created on 2018-07-19 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).


Wikidata is very structured data which is its strength. For most people, name is available only as complete name (so one might need to resort to e.g. [`humaniformat`](https://github.com/Ironholds/humaniformat) to extract first names and so). 

In the query below, built thanks to [the online helper](https://query.wikidata.org/) as I had done [in this blog post](https://masalmon.eu/2017/08/06/p1/) I filter by date of birth because old names&occupations might not be very relevant. The data is in a long format, so there can be more than one line by person. 

``` r
query <- 'SELECT DISTINCT ?itemLabel ?family_nameLabel ?given_nameLabel ?sex_or_gender ?sex_or_genderLabel ?nameLabel ?occupationLabel ?official_nameLabel ?birth_nameLabel ?honorific_suffixLabel ?date_of_birth WHERE {
  ?item wdt:P31 wd:Q5;
    wdt:P27 wd:Q142;
  wdt:P569 ?born .
FILTER (?born >= "1921-01-01T00:00:00Z"^^xsd:dateTime).
OPTIONAL { ?item wdt:P734 ?family_name. }
SERVICE wikibase:label { bd:serviceParam wikibase:language "fr". }
OPTIONAL { ?item wdt:P735 ?given_name. }
OPTIONAL { ?item wdt:P21 ?sex_or_gender. }
OPTIONAL { ?item wdt:P2561 ?name. }
OPTIONAL { ?item wdt:P106 ?occupation. }
OPTIONAL { ?item wdt:P1448 ?official_name. }
OPTIONAL { ?item wdt:P1477 ?birth_name. }
OPTIONAL { ?item wdt:P1035 ?honorific_suffix. }
OPTIONAL { ?item wdt:P569 ?date_of_birth. }
}
LIMIT 1000'

results <- WikidataQueryServiceR::query_wikidata(query)
#> 1000 rows were returned by WDQS
str(results)
#> 'data.frame':    1000 obs. of  11 variables:
#>  $ itemLabel            : chr  "Henriette Walter" "Mehdi Baala" "Georges Fenech" "Bernard Werber" ...
#>  $ family_nameLabel     : chr  "Walter" "" "Fenech" "Werber" ...
#>  $ given_nameLabel      : chr  "Henriette" "Mehdi" "Georges" "Bernard" ...
#>  $ sex_or_gender        : chr  "http://www.wikidata.org/entity/Q6581072" "http://www.wikidata.org/entity/Q6581097" "http://www.wikidata.org/entity/Q6581097" "http://www.wikidata.org/entity/Q6581097" ...
#>  $ sex_or_genderLabel   : chr  "féminin" "masculin" "masculin" "masculin" ...
#>  $ nameLabel            : logi  NA NA NA NA NA NA ...
#>  $ occupationLabel      : chr  "linguiste" "athlète" "personnalité politique" "écrivain de science-fiction" ...
#>  $ official_nameLabel   : chr  "" "" "" "" ...
#>  $ birth_nameLabel      : chr  "" "" "" "" ...
#>  $ honorific_suffixLabel: logi  NA NA NA NA NA NA ...
#>  $ date_of_birth        : chr  "1929-03-05T00:00:00Z" "1978-08-17T00:00:00Z" "1954-10-26T00:00:00Z" "1961-09-18T00:00:00Z" ...
```

Created on 2018-07-19 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

I let Wikidata output gender as text (in French) and item, because items have IDs so can be used no matter the locale.

**Comment by sckott** [comment]
thanks for all the digging @maelle !

**Comment by kylevoyto** [comment]
I don't know whether we should close the original issue. The more complex tasks can be improved upon. The most recent commit https://github.com/ropensci/charlatan/pull/83/commits/e82828563794e0a3262600a7f78420f7ab5a2642 has changes to person provider that are valuable regardless, so they could be included in a different PR.

**Comment by kylevoyto** [comment]
I should note that it's still possible to have double first/last names, but they're very unlikely. Still can be fixed in the future

**Comment by sckott** [comment]
great, thanks @kylevoyto !  LGTM. Are you comfortable with me merging this now?

**Comment by kylevoyto** [comment]
Yes, I think so

**Comment by sckott** [comment]
Okay, great, thanks for all your work on this.

**Pull request merged**
