### PR TITLE
extends choices generate and NL jobs

### PR DESCRIPTION
**Pull request by markbaas**
Extends ch_generate choices

As I wanted to use this for the nl NL locale I also had to add nl support to jobs.

### CODE REVIEW

**Comment by sckott** [comment]
Thanks!

- When I installed and ran document() locally it updated the manual file, and NAMESPACE file, and added a missing ch_generate.Rd file, make sure to install and build docs locally and push up changes
- try not to introduce white space changes
- Would you be okay just using `AddressProvider`?  I ask because `AddressProvider` has a lot of methods. If we made a separate `ch_` function for every method within `AddressProvider` that would be I think too many functions. I realize that `ch_generate` works by using `ch_` functions, but I could refactor it to work with the R6 classes instead, opening it up to more options. Thoughts?

**Comment by markbaas** [comment]
> 
> 
> Thanks!
> 
>     * tests aren't passing, make sure tests are passing - if a failure isn't related to your changes, then thats okay and not your problem
> 

Let me check this.

>     * When I installed and ran document() locally it updated the manual file, and NAMESPACE file, and added a missing ch_generate.Rd file, make sure to install and build docs locally and push up changes
> 

Will check it as well.

>     * try not to introduce white space changes

VSCode trims these automatically. There are not too many though, perhaps it is a good idea to trim these when touching the files?

> 
>     * Would you be okay just using `AddressProvider`?  I ask because `AddressProvider` has a lot of methods. If we made a separate `ch_` function for every method within `AddressProvider` that would be I think too many functions. I realize that `ch_generate` works by using `ch_` functions, but I could refactor it to work with the R6 classes instead, opening it up to more options. Thoughts?

I will definitely be okay with that. I think the non-provider files are a bit duplicate functionality. I really only implemented the address one so it would work with generator. Let's refactor the generate then so it would solely work with providers. I can help you out with this next week I think.

**Comment by sckott** [comment]
> Let's refactor the generate then so it would solely work with providers. I can help you out with this next week I think.

Great, sounds good

**Comment by sckott** [comment]
Thanks @markbaas Sorry for delay, was on leave. Is this PR ready for me to look at now?

**Comment by sckott** [comment]
I'll cherry pick the jobs provider NL work out of this into this next submission to cran

**Comment by sckott** [comment]
closing via  81e16c5 

Pulled in only changes to addresses and providers specific to NL

other items can be considered in a separate PR

**Pull request closed without merging**
