### PR TITLE
Update charlatan_vignette.Rmd

### LINKED ISSUE #4: possibly provide lazy input to ch_generate, other fxns?

### PR DESCRIPTION
**Pull request by starship9**
Added an example, using the ch_generate() function in conjunction with sample() and lapply() to add missing data

## Related Issue

https://github.com/ropensci/charlatan/issues/85

### CODE REVIEW

**Comment by sckott** [comment]
thanks very much @starship9 

I think @maelle meant  with the `MissingDataProvider` class in this package (is that right Maëlle?) - maybe we can keep your example, but can you also add one with `MissingDataProvider`

**Comment by maelle** [comment]
Yep sorry for the lack of info in the initial issue

**Comment by sckott** [comment]
any thoughts @starship9 ?

**Comment by starship9** [comment]
I'm on it

**Comment by sckott** [comment]
@starship9  to make changes to this pull request instead of opening a new one go to your fork and branch of this repo at https://github.com/starship9/charlatan/tree/patch-1 - And edit the file or files there and it will automatically get added here!

**Comment by sckott** [comment]
thanks @starship9 !

for the first example it'd be good to show the reader what the result is. if the example is rendered all you see is the code, and not the output. so you could do e.g., 

```r
testDFNA <- as.data.frame(lapply(ch_generate(), function(addNA) addNA[sample(c(TRUE, NA), prob = c(0.8, 0.2), size = length(addNA), replace = TRUE)]))
testDFNA
```

**Comment by sckott** [comment]
any thoughts @starship9 ?

**Comment by KKulma** [comment]
happy to pick it up, if it's still needed?

**Comment by sckott** [comment]
that'd be great, thanks @KKulma ! probably easiest to start  a new PR from your own fork since you wouldn't have access to the fork here

**Comment by KKulma** [comment]
exactly. Working on it!

**Pull request closed without merging**
