### PR TITLE
remove duplicates and sort names

### PR DESCRIPTION
**Pull request by MartinMSPedersen**
## Description

I have identified some duplicates names with sort, uniq, grep and removed these.
I have also sorted the names so it is easier in the future to add more names without
creating new duplicates.

### CODE REVIEW

**Comment by sckott** [comment]
@MartinMSPedersen thanks for this!  

however, is there a way for you to sort these based on the non-unicode text? .e.,g `"\u017bak"` is rendered as `Żak` but is in the `U` section alphebetically I assume because it starts with `u`. or is it not possible to sort by the actual letters from the unicode representation?

**Comment by MartinMSPedersen** [comment]
> @MartinMSPedersen thanks for this!
> 
> however, is there a way for you to sort these based on the non-unicode text? .e.,g `"\u017bak"` is rendered as `Żak` but is in the `U` section alphebetically I assume because it starts with `u`. or is it not possible to sort by the actual letters from the unicode representation?

OK. I will do that. It might take a few days because it is not trivial.

**Comment by sckott** [comment]
thanks very much. I didn't know how to sort them off the top of my head - otherwise would suggest that

**Comment by MartinMSPedersen** [comment]
> thanks very much. I didn't know how to sort them off the top of my head - otherwise would suggest that

eg. stringi::stri_sort(person_first_names_female_bg_bg, locale='bg_bg')
etc.
I will do the work soon.

**Comment by sckott** [comment]
@MartinMSPedersen thanks, more work to do on sorting, or are you done already?

**Comment by MartinMSPedersen** [comment]
It think I am done for this time.

**Comment by sckott** [comment]
Okay, thanks very much for this work @MartinMSPedersen

**Pull request merged**
