### PR TITLE
Fix typo in docs for ch_generate

### LINKED ISSUE #4: possibly provide lazy input to ch_generate, other fxns?

### PR DESCRIPTION
**Pull request by j450h1**

### CODE REVIEW

**Comment by sckott** [comment]
thanks! 

Can you make the change in the equivalent R file as well? See https://github.com/ropensci/charlatan/blob/master/R/generate.R#L5

**Comment by j450h1** [comment]
Sure will do.

**Comment by j450h1** [comment]
Should be good now. Probably added 1 more commit then necessary, so apologies I'm a bit rusty on git pr process.

**Comment by sckott** [comment]
Looks good, thanks for the fix!

**Pull request merged**
